title: "Rahul's blog"
author: "Rahul Gadre"
description: A cloud engineer who is passionate about learning new technologies and solving infrastructure issues using Cloud and DevOps technologies. Want to get in touch? Send me an email at rahul (at) rahulgadre.com.
#description: "Made with <b style=\"color: #f45;\">&lt;3</b> by <b><a href=\"https://github.com/rahulgadre\">@rahulgadre</a></b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true               # show a sidebar instead of the usual header
show_excerpts: false         # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: true       # show the site description in the sidebar
show_title: false            # always keep the site title visible

# Styling

dark_header: false           # always keep the header dark
minimal: false               # use simpler style

# Menu

navigation:
  - {file: "index.html", icon: home}
  - {file: "projects.md", icon: project-diagram}

external:                    # see http://fontawesome.com/icons
#  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
   - {title: Github, icon: github, url: "https://github.com/rahulgadre"}
   - {title: Twitter, icon: twitter, url: "https://twitter.com/rggadre"}
   - {title: Mail, icon: envelope, url: "mailto:rahul@rahulgadre.com"}
   - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/rahulgadre/"}
   - {title: Website, icon: globe, url: "https://rahulgadre.com/"}
 #  - {title: Dev, icon: dev, url: "https://dev.to/rahulgadre"}
   
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
 disqus_shortname: "https-rahulgadre-github-io"      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
 - jekyll-feed
